logging:
  config: classpath:log4j2.xml
server:
  port: 
  context-path: 
spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    execution: 
    druid1: 
      min-idle: 1
      max-active: 20
      initial-size: 1
      max-wait: 6000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 50
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 30000 
      validation-query: SELECT 'ZTM' FROM DUAL 
      test-while-idle: true  
      test-on-borrow: false  
      test-on-return: false
mybatis: 
  mapper-locations: 
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
pagehelper:
  helper-dialect: oracle