package cn.northpark.weixin.dao;

import cn.northpark.weixin.entity.Astro;
import java.util.List;

public interface AstroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_astro
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_astro
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int insert(Astro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_astro
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    Astro selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_astro
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    List<Astro> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_astro
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int updateByPrimaryKey(Astro record);
}