package cn.northpark.weixin.dao;

import cn.northpark.weixin.entity.Member;
import cn.northpark.weixin.entity.MemberWithBLOBs;
import java.util.List;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    MemberWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    List<Member> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table np_member
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    int updateByPrimaryKey(Member record);
}