package cn.northpark.weixin.dao;

import java.util.List;

import cn.northpark.weixin.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_user
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_user
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_user
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_user
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int updateByPrimaryKey(User record);
}