package cn.northpark.weixin.dao;

import java.util.List;

import cn.northpark.weixin.entity.UserProfile;

public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_userprofile
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_userprofile
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int insert(UserProfile record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_userprofile
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    List<UserProfile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_userprofile
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    int updateByPrimaryKey(UserProfile record);
}