package cn.northpark.weixin.entity;

public class Astro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_astro.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_astro.wx_cop_userid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String wxCopUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_astro.xzname
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String xzname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_astro.addtime
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_astro.type
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_astro.status
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_astro.id
     *
     * @return the value of bc_astro.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_astro.id
     *
     * @param id the value for bc_astro.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_astro.wx_cop_userid
     *
     * @return the value of bc_astro.wx_cop_userid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getWxCopUserid() {
        return wxCopUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_astro.wx_cop_userid
     *
     * @param wxCopUserid the value for bc_astro.wx_cop_userid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setWxCopUserid(String wxCopUserid) {
        this.wxCopUserid = wxCopUserid == null ? null : wxCopUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_astro.xzname
     *
     * @return the value of bc_astro.xzname
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getXzname() {
        return xzname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_astro.xzname
     *
     * @param xzname the value for bc_astro.xzname
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setXzname(String xzname) {
        this.xzname = xzname == null ? null : xzname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_astro.addtime
     *
     * @return the value of bc_astro.addtime
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_astro.addtime
     *
     * @param addtime the value for bc_astro.addtime
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime == null ? null : addtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_astro.type
     *
     * @return the value of bc_astro.type
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_astro.type
     *
     * @param type the value for bc_astro.type
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_astro.status
     *
     * @return the value of bc_astro.status
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_astro.status
     *
     * @param status the value for bc_astro.status
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}