package cn.northpark.weixin.entity;

public class Health {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.id
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.openid
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.name
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.phone
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.address
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.project
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.agreement
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private Integer agreement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.addtime
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private String addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.status
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_health.info
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.id
     *
     * @return the value of np_health.id
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.id
     *
     * @param id the value for np_health.id
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.openid
     *
     * @return the value of np_health.openid
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.openid
     *
     * @param openid the value for np_health.openid
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.name
     *
     * @return the value of np_health.name
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.name
     *
     * @param name the value for np_health.name
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.phone
     *
     * @return the value of np_health.phone
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.phone
     *
     * @param phone the value for np_health.phone
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.address
     *
     * @return the value of np_health.address
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.address
     *
     * @param address the value for np_health.address
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.project
     *
     * @return the value of np_health.project
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.project
     *
     * @param project the value for np_health.project
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.agreement
     *
     * @return the value of np_health.agreement
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public Integer getAgreement() {
        return agreement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.agreement
     *
     * @param agreement the value for np_health.agreement
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setAgreement(Integer agreement) {
        this.agreement = agreement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.addtime
     *
     * @return the value of np_health.addtime
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.addtime
     *
     * @param addtime the value for np_health.addtime
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime == null ? null : addtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.status
     *
     * @return the value of np_health.status
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.status
     *
     * @param status the value for np_health.status
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_health.info
     *
     * @return the value of np_health.info
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_health.info
     *
     * @param info the value for np_health.info
     *
     * @mbggenerated Thu Jul 19 15:45:13 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}