package cn.northpark.weixin.entity;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.id
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.openid
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.name
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.gender
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.birth
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.phone
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.address
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.recommender
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String recommender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.addtime
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.status
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column np_member.info
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.id
     *
     * @return the value of np_member.id
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.id
     *
     * @param id the value for np_member.id
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.openid
     *
     * @return the value of np_member.openid
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.openid
     *
     * @param openid the value for np_member.openid
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.name
     *
     * @return the value of np_member.name
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.name
     *
     * @param name the value for np_member.name
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.gender
     *
     * @return the value of np_member.gender
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.gender
     *
     * @param gender the value for np_member.gender
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.birth
     *
     * @return the value of np_member.birth
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.birth
     *
     * @param birth the value for np_member.birth
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.phone
     *
     * @return the value of np_member.phone
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.phone
     *
     * @param phone the value for np_member.phone
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.address
     *
     * @return the value of np_member.address
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.address
     *
     * @param address the value for np_member.address
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.recommender
     *
     * @return the value of np_member.recommender
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getRecommender() {
        return recommender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.recommender
     *
     * @param recommender the value for np_member.recommender
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setRecommender(String recommender) {
        this.recommender = recommender == null ? null : recommender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.addtime
     *
     * @return the value of np_member.addtime
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.addtime
     *
     * @param addtime the value for np_member.addtime
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime == null ? null : addtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.status
     *
     * @return the value of np_member.status
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.status
     *
     * @param status the value for np_member.status
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column np_member.info
     *
     * @return the value of np_member.info
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column np_member.info
     *
     * @param info the value for np_member.info
     *
     * @mbggenerated Mon Jul 30 16:45:42 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}