package cn.northpark.weixin.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.username
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.email
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.tail_slug
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String tailSlug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.password
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.headspanclass
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String headspanclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.headspan
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String headspan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.headpath
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String headpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.meta
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String meta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.blogsite
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String blogsite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.date_joined
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String dateJoined;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.last_login
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.qq_openid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String qqOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.qq_info
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String qqInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.is_del
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.wx_openid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String wxOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_user.wx_info
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String wxInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.id
     *
     * @return the value of bc_user.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.id
     *
     * @param id the value for bc_user.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.username
     *
     * @return the value of bc_user.username
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.username
     *
     * @param username the value for bc_user.username
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.email
     *
     * @return the value of bc_user.email
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.email
     *
     * @param email the value for bc_user.email
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.tail_slug
     *
     * @return the value of bc_user.tail_slug
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getTailSlug() {
        return tailSlug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.tail_slug
     *
     * @param tailSlug the value for bc_user.tail_slug
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setTailSlug(String tailSlug) {
        this.tailSlug = tailSlug == null ? null : tailSlug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.password
     *
     * @return the value of bc_user.password
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.password
     *
     * @param password the value for bc_user.password
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.headspanclass
     *
     * @return the value of bc_user.headspanclass
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getHeadspanclass() {
        return headspanclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.headspanclass
     *
     * @param headspanclass the value for bc_user.headspanclass
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setHeadspanclass(String headspanclass) {
        this.headspanclass = headspanclass == null ? null : headspanclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.headspan
     *
     * @return the value of bc_user.headspan
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getHeadspan() {
        return headspan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.headspan
     *
     * @param headspan the value for bc_user.headspan
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setHeadspan(String headspan) {
        this.headspan = headspan == null ? null : headspan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.headpath
     *
     * @return the value of bc_user.headpath
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getHeadpath() {
        return headpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.headpath
     *
     * @param headpath the value for bc_user.headpath
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setHeadpath(String headpath) {
        this.headpath = headpath == null ? null : headpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.meta
     *
     * @return the value of bc_user.meta
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getMeta() {
        return meta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.meta
     *
     * @param meta the value for bc_user.meta
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setMeta(String meta) {
        this.meta = meta == null ? null : meta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.blogsite
     *
     * @return the value of bc_user.blogsite
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getBlogsite() {
        return blogsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.blogsite
     *
     * @param blogsite the value for bc_user.blogsite
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setBlogsite(String blogsite) {
        this.blogsite = blogsite == null ? null : blogsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.date_joined
     *
     * @return the value of bc_user.date_joined
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getDateJoined() {
        return dateJoined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.date_joined
     *
     * @param dateJoined the value for bc_user.date_joined
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setDateJoined(String dateJoined) {
        this.dateJoined = dateJoined == null ? null : dateJoined.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.last_login
     *
     * @return the value of bc_user.last_login
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.last_login
     *
     * @param lastLogin the value for bc_user.last_login
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setLastLogin(String lastLogin) {
        this.lastLogin = lastLogin == null ? null : lastLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.qq_openid
     *
     * @return the value of bc_user.qq_openid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getQqOpenid() {
        return qqOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.qq_openid
     *
     * @param qqOpenid the value for bc_user.qq_openid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setQqOpenid(String qqOpenid) {
        this.qqOpenid = qqOpenid == null ? null : qqOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.qq_info
     *
     * @return the value of bc_user.qq_info
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getQqInfo() {
        return qqInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.qq_info
     *
     * @param qqInfo the value for bc_user.qq_info
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setQqInfo(String qqInfo) {
        this.qqInfo = qqInfo == null ? null : qqInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.is_del
     *
     * @return the value of bc_user.is_del
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.is_del
     *
     * @param isDel the value for bc_user.is_del
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.wx_openid
     *
     * @return the value of bc_user.wx_openid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.wx_openid
     *
     * @param wxOpenid the value for bc_user.wx_openid
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_user.wx_info
     *
     * @return the value of bc_user.wx_info
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getWxInfo() {
        return wxInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_user.wx_info
     *
     * @param wxInfo the value for bc_user.wx_info
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setWxInfo(String wxInfo) {
        this.wxInfo = wxInfo == null ? null : wxInfo.trim();
    }
}