package cn.northpark.weixin.entity;

public class UserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.user_id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.name
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.nickname
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.language
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.location
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.courseware
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String courseware;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.gender
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.tel
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.year_of_birth
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String yearOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.level_of_education
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String levelOfEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.allow_certificate
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private Boolean allowCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.country
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.is_del
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.user_slug
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String userSlug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.meta
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String meta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.mailing_address
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String mailingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.goals
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String goals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_userprofile.city
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.id
     *
     * @return the value of bc_userprofile.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.id
     *
     * @param id the value for bc_userprofile.id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.user_id
     *
     * @return the value of bc_userprofile.user_id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.user_id
     *
     * @param userId the value for bc_userprofile.user_id
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.name
     *
     * @return the value of bc_userprofile.name
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.name
     *
     * @param name the value for bc_userprofile.name
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.nickname
     *
     * @return the value of bc_userprofile.nickname
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.nickname
     *
     * @param nickname the value for bc_userprofile.nickname
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.language
     *
     * @return the value of bc_userprofile.language
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.language
     *
     * @param language the value for bc_userprofile.language
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.location
     *
     * @return the value of bc_userprofile.location
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.location
     *
     * @param location the value for bc_userprofile.location
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.courseware
     *
     * @return the value of bc_userprofile.courseware
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getCourseware() {
        return courseware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.courseware
     *
     * @param courseware the value for bc_userprofile.courseware
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setCourseware(String courseware) {
        this.courseware = courseware == null ? null : courseware.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.gender
     *
     * @return the value of bc_userprofile.gender
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.gender
     *
     * @param gender the value for bc_userprofile.gender
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.tel
     *
     * @return the value of bc_userprofile.tel
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.tel
     *
     * @param tel the value for bc_userprofile.tel
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.year_of_birth
     *
     * @return the value of bc_userprofile.year_of_birth
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getYearOfBirth() {
        return yearOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.year_of_birth
     *
     * @param yearOfBirth the value for bc_userprofile.year_of_birth
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setYearOfBirth(String yearOfBirth) {
        this.yearOfBirth = yearOfBirth == null ? null : yearOfBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.level_of_education
     *
     * @return the value of bc_userprofile.level_of_education
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getLevelOfEducation() {
        return levelOfEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.level_of_education
     *
     * @param levelOfEducation the value for bc_userprofile.level_of_education
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setLevelOfEducation(String levelOfEducation) {
        this.levelOfEducation = levelOfEducation == null ? null : levelOfEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.allow_certificate
     *
     * @return the value of bc_userprofile.allow_certificate
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public Boolean getAllowCertificate() {
        return allowCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.allow_certificate
     *
     * @param allowCertificate the value for bc_userprofile.allow_certificate
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setAllowCertificate(Boolean allowCertificate) {
        this.allowCertificate = allowCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.country
     *
     * @return the value of bc_userprofile.country
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.country
     *
     * @param country the value for bc_userprofile.country
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.is_del
     *
     * @return the value of bc_userprofile.is_del
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.is_del
     *
     * @param isDel the value for bc_userprofile.is_del
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.user_slug
     *
     * @return the value of bc_userprofile.user_slug
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getUserSlug() {
        return userSlug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.user_slug
     *
     * @param userSlug the value for bc_userprofile.user_slug
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setUserSlug(String userSlug) {
        this.userSlug = userSlug == null ? null : userSlug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.meta
     *
     * @return the value of bc_userprofile.meta
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getMeta() {
        return meta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.meta
     *
     * @param meta the value for bc_userprofile.meta
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setMeta(String meta) {
        this.meta = meta == null ? null : meta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.mailing_address
     *
     * @return the value of bc_userprofile.mailing_address
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getMailingAddress() {
        return mailingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.mailing_address
     *
     * @param mailingAddress the value for bc_userprofile.mailing_address
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setMailingAddress(String mailingAddress) {
        this.mailingAddress = mailingAddress == null ? null : mailingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.goals
     *
     * @return the value of bc_userprofile.goals
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getGoals() {
        return goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.goals
     *
     * @param goals the value for bc_userprofile.goals
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setGoals(String goals) {
        this.goals = goals == null ? null : goals.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_userprofile.city
     *
     * @return the value of bc_userprofile.city
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_userprofile.city
     *
     * @param city the value for bc_userprofile.city
     *
     * @mbggenerated Fri May 04 13:40:47 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}